### ISSUE TITLE
IDiaEnumStackFrames::Next has no return value

### ISSUE THREAD

**Issue by henke37** [southpolenator/ComInterfaces#3]
The `Next` method of the `IDiaEnumStackFrames` interface needs to return the status so that the caller can tell the difference between a successful call and there not being any more items to fetch.

**Comment by southpolenator** [comment]
Interfaces that don't return values are checked by Marshaller and they throw exception if HRESULT represents error. For interfaces that user needs to implement HRESULT must be returned or it is always S_OK. There are now "clone" of interfaces in DIA.NoExceptions namespace that return HRESULT instead of throwing exception. Interfaces that throw exceptions can be easily casted to ones that don't throw and vice versa.
